version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@storybook/cli"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
    - 9.0.11
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: rc-notification
    versions:
    - 4.5.4
